// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emfddmyurnlsvpvlplzj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtZmRkbXl1cm5sc3ZwdmxwbHpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MjAyMTYsImV4cCI6MjA3NDI5NjIxNn0.4uZi8dpMFlTsfm64hVSffLqXqwqtNeF2kNNR1HGi-Fc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});